import Head from "next/head";
import MaininfoEdit from "~/utils/components/Forms/MaininfoEdit";
import Footer from "~/utils/components/Footer";
import Navbar from "~/utils/components/Navbar";
import StepCard from "~/utils/components/RecipePage/StepCard";
import StepsInput from "./StepsInput";
import { useState } from "react";

export default function Create() {
  const [steps, setSteps] = useState<string[]>([]);

  return (
    <>
      <Head>
        <title>CookNet</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className=" flex min-h-screen flex-col items-center justify-center bg-white ">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          {/* <RecipeHeader /> */}
          <MaininfoEdit />
          <StepsInput onChange={(steps) => setSteps(steps)} />
        </div>
      </main>
      <Footer />
    </>
  );
}
