import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import CallToAction from "~/utils/components/CallToAction";
import CategoriesSection from "~/utils/components/CategoriesSelection";
import Footer from "~/utils/components/Footer";
import Header from "~/utils/components/Header";
import Navbar from "~/utils/components/Navbar";
import RecipeCard from "~/utils/components/RecipeCard";

export default function Home() {
  return (
    <>
      <Head>
        <title>CookNet</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex w-full flex-col items-center justify-center gap-12 px-4 py-16 ">
          <Header />
          <CategoriesSection />
          <div className="grid w-full grid-cols-3 gap-4">
            <RecipeCard />
            <RecipeCard />
            <RecipeCard />
            <RecipeCard />
            <RecipeCard />
            <RecipeCard />
          </div>
          <CallToAction />
        </div>
      </main>
      <Footer />
    </>
  );
}
